apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: du-data
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        class: sc-kafka
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        kraftMetadata: shared
