apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-0
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-1
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-03
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-2
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-04
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-3
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw04
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-05
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-4
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw05
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-06
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-5
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw06
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-zookeeper-07
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-fr-data-zookeeper-6
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/zookeeper
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw07
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-zookeeper
  volumeMode: Filesystem
