apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-0
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-1
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-03
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-2
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-04
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-3
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw04
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-05
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-4
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw05
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-06
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-5
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw06
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-kafka-07
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-fr-data-kafka-6
    namespace: ns-data-hc
  hostPath:
    path: /var/mnt/datavol2/kafka
    type: ''
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fkw07
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-kafka
  volumeMode: Filesystem
