apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: ns-data
  labels:
    strimzi.io/cluster: ab-data
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        class: sc-kafka
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        kraftMetadata: shared
